# Capstone Assignment 1

---
⚠️**Notebook Instruction:**
- <..> in this notebook are the placeholders for your codes.
- You can insert multiple lines of code into a placeholder <..>.
- Feel free to insert additional cell(s) as you need.
- ⬇️ Enter your name below as a string below.

In [1]:
Name = "TAN HUI HUI JENNY "

<hr/>

Question 1 - Variable & Operators <br/>
Question 2 - String, List, Tuple, Dictionary <br/>
Question 3 - if-else, conditionals <br/>
Question 4 - for loop <br/>
Question 5 - while loop <br/>
Question 6 - functions

<hr/>

# Question 1 - Variables & Operators

> **[ Question 1A ]** <br/>
Assign 59 to a variable <b>floor_area_1</b> <br/>

In [2]:
floor_area_1 = 59

> **[ Question 1B ]** <br/>
Assign 82 to a variable <b>floor_area_2</b> 

In [3]:
floor_area_2 = 82

> **[ Question 1C ]** <br/>
>- Prompt user to input a value and assign the value to a variable called <b>floor_area_3</b>. 
>- User will see \"Enter the floor area in square meters = \" (double quotes not included)
>- Assume user keys in <b>60</b>.
>- Change the data type of the variable, allowing the variable to be used in mathematical operations (e.g. summation and deduction)
>
> 📑  <i>You can assume that the user will not input anything other than numbers. So there is no need to check for errors.</i><br/>


In [4]:
floor_area_3 = int(input("Enter the floor area in square meters = "))

Enter the floor area in square meters = 60


In [5]:
floor_area_3

60

> **[ Question 1D ]**  <br/>
>
>Write the code to calculate the average of the three floor_area variables - **floor_area_1**, **floor_area_2**, and **floor_area_3**, and store the average value into a variable **floor_area_mean**.<br/>



In [6]:
floor_area_mean = (floor_area_1 + floor_area_2 + floor_area_3)/3
print(floor_area_mean)

67.0


In [7]:
# Method 2 : Using numpy library is normally imported for most python projects
# Need to store variables as list
 
import numpy as np
floor_area_mean  = np.mean([floor_area_1,floor_area_2,floor_area_3])
print(floor_area_mean)

67.0


In [8]:
# Method 3: calculating mean
# Need to store variables as list

from statistics import mean

floor_area_mean  = mean([floor_area_1,floor_area_2,floor_area_3])
print(floor_area_mean)

67


In [9]:
floor_areas = [floor_area_1,floor_area_2,floor_area_3]

> **[ Question 1E ]** <br/>
Print out the value stored in <b>floor_area_mean</b> to produce the same output below: <br/>

>Example output when the average floor area is 67 is shown below: <br/>
\"The average floor area of the HDB units is 67.0 square meters.\"

> 📑  <i> your code should work with any value stored in the **floor_area_mean**</i><br/>


In [10]:
print(f"The average floor area of the HDB units is {floor_area_mean} square meters.") 

The average floor area of the HDB units is 67 square meters.


## Question 2 - String, List, Tuple, Dictionary

> **[ Question 2A ]** <br/>
>1) Decide on a data type (either String, List, Tuple, or Dictionary) to use for the following use case: <br/>
>- I want to store the following information in a variable so that I can retrieve the town (e.g. Bedok), based on the postal code.<br/>
>- I want to be able to change some of the values (e.g. Bedok) associated with a particular postal code from time to time.<br/>
>- There should be no duplicated postal codes stored in the variable
>- Order of the postal codes does not matter.<br/>
>
>2) When you have decided, create such a variable called <b>postal_to_town</b> and store the following information into it:<br/>
>- 470703 --> Bedok 
>- 530406 --> Hougang 
>- 460002 --> BEDOK
>- 330000 --> Clementi

In [11]:
# Store the postal code and town info in a dictionary

postal_to_town = {470703 : "Bedok",
                  530406 : "Hougang",
                  460002 : "BEDOK",
                  330000 : "Clementi"}

print(postal_to_town)

{470703: 'Bedok', 530406: 'Hougang', 460002: 'BEDOK', 330000: 'Clementi'}


> **[ Question 2B ]** <br/>
Change the town for the postal code 460002 to Sentence case (only first character is capitalized) <br/>
You're **required to use a string method** to change the town's name to Sentence case.<br/>
Print out the town for postal code 46002 after you have changed the value, you should have the output as below:<br/>

>Bedok

In [12]:
# Edit the value of a specific key in a dictionary
# Here we want to capitalize the first letter of the town name of the key 460002.
postal_to_town[460002]= postal_to_town[460002].capitalize() 
print(postal_to_town[460002])

Bedok


> **[ Question 2C ]** <br/>
>1) Decide on a data type (either String, List, Tuple, or Dictionary) to use for the following use case:
>
>- I want to read in values and store them as I read them in sequentially.
>- Order matters.
>- Repeated values are ok.
>- I want to be able to add/remove some of the items too
>
>2) When you have decided, create such a variable called <b>yearmonth</b> and store the following information into it:
>- 2015-07
>- 2016-04
>- 2014-04
>- 2015-12
>- 2016-12

In [13]:
# Store the elements in a list rather than a tuple which is immutable (i.e. can't change the elements)

yearmonth = ["2015-07", "2016-04", "2014-04", "2015-12", "2016-12", "2016-12"]


> **[ Question 2D ]** <br/>
Retrieve the 3rd item in your variable **yearmonth**, then separately store the year and month into two variables called **year** and **month** respectively. <br/>
>Using the variables **year** and **month**, print the **year** and **month** in a statement that looks like this: <br/>

>The unit was sold in year 2014, month 4 of the year.<br/>

> 📑  <i> Note: You can use a string method, or index slicing, or any other method that you think is suitable. Also feel free to define new variable(s) if needed.</i><br/>

In [14]:
yearmonth[2]
year = yearmonth[2][:4]
month = yearmonth[2][-2:]

print(f"The unit was sold in year {year}, month {int(month)} of the year.")

The unit was sold in year 2014, month 4 of the year.


# Question 3 - If-Else

> **[ Question 3A ]** <br/>
Assign <b>True</b> to a variable <b>multistorey_carpark</b> <br/>

In [15]:
multistorey_carpark = True

> **[ Question 3B ]** <br/>
Assign a string value <b>high</b> to a variable **floor_type** <br/>

>📑  <i> Note: Assume there are only 2 categories of **floor_type**: a) *high* and b) *low*.</i>


In [16]:
floor_type ="high"

> **[ Question 3C ]** <br/>
Fill in the if-else logic below according to the rules here:<br/>
>- If the unit is on high floor and has a multistorey carpark, it meets all requirements of the client<br/>
>- If the unit is on high floor but does not have a multistorey carpark, it only meets the key criterion of the client<br/>
>- If the unit is on low floor and has a multistorey a carpark, it only meets the non-critical criterion of the client <br/>
>- If the unit is on low floor and does not have a multistorey carpark, it meets none of the requirements of the client <br/>


In [17]:
if floor_type:
 and multistorey_carpark:
    print("This unit meets all requirements of the client")
elif floor_type:
    print("This unit only meets the key criterion of the client")
elif multistorey_carpark:
    print("This unit only meets the non-critical criterion of the client")
elif floor_type !="high" and multistorey_carpark == False:
    print("This unit meets none of the requirements of the client")

This unit meets all requirements of the client


# Question 4 - For Loop 

> **[ Question 4A ]**  <br/>
Initialise a list with six values [20, 5, 45, 9, 1, 15] (in precisely this sequence), and store it into a variable, <b>age_list</b>. 

>📑 *Note: These are the age of six different HDB blocks, in number of years*

In [18]:
age = [20,5,45,9,1,15]

> **[ Question 4B ]** <br/>
Write the code to loop through the list <b>age_list</b>, and print out the following:<br/>
>- if the age of the HDB block is older than 20 years old, print <i>"Matured Estate - x years"</i> where x is the age in number.<br/>
>- if the age of the HDB block is 20 or below and at least 5, print <i>"Non-Matured Estate - x years"</i> where x is that number.<br/>
>- if the age of the HDB block is less than 5, it should be ignored. 

> Based on your list initialised in Question 4A, after running the code below, you should see:<br/>
> Non-Matured Estate - 20 years<br/>
> Non-Matured Estate - 5 years<br/>
> Matured Estate - 45 years<br/>
> Non-Matured Estate - 9 years<br/>
> Non-Matured Estate - 15 years<br/>


In [19]:
for i in age:
    if i >=5:
        if i > 20:
            print(f"Mature Estate - {i} years")
        else: 
            i <=20
            print(f"Non-Mature Estate - {i} years")        

Non-Mature Estate - 20 years
Non-Mature Estate - 5 years
Mature Estate - 45 years
Non-Mature Estate - 9 years
Non-Mature Estate - 15 years


>**[ Question 4C ]** <br/>
In the cell below, modify your code from 4 b) such that:<br/>
You initialise a variable <b>shortlisted</b> as an empty list (code is provided, no modification is needed for this first line of code). <br/>
Then inside your <b>for loop</b>, you should add the age of the HDB block to the list **shortlisted** ONLY if the age is not more than 20 years old but is at least 5 years old.<br/>
After you exit from the <b>for loop</b>, print out that number of items in the list.<br/>

> Based on your list initialised in Question 4A), after running your codes below, you should see:<br/>
Non-Matured Estate - 20 years <br/>
Non-Matured Estate - 5 years <br/>
Matured Estate - 45 years <br/>
Non-Matured Estate - 9 years <br/>
Non-Matured Estate - 15 years <br/>
Length of the list is 4 <br/>

> 📑  <i> Note: You can use .append() and .remove() functions from a list object to add and drop items</i><br/>

In [20]:
shortlisted = []

for i in age:
    if i >=5:
        if i > 20:
            print(f"Mature Estate - {i} years")
        else: 
            i <=20
            shortlisted.append(i)
            print(f"Non-Mature Estate - {i} years")        

print(f"Length of the shortlist is {len(shortlisted)}")

Non-Mature Estate - 20 years
Non-Mature Estate - 5 years
Mature Estate - 45 years
Non-Mature Estate - 9 years
Non-Mature Estate - 15 years
Length of the shortlist is 4


# Question 5 - While Loop 

> **[ Question 5A ]** <br/>
Prompt a user for an input with 'Tell me the floor area in Square Meters'.<br/>
Then, cast the input into an integer.<br/>
Then, convert that Square Meters into Square Feet.<br/>
Then, print out the floor area in Square Feet.<br/>

>For example, if the user keyed in 110 square meters, the output would look like:<br/>
Tell me the floor area in Square Meters: 110 <br/>
The floor area in square meters converted to square feet is: 1184.04<br/>

> 📑  <i> Note:1 meter<sup>2</sup> = 10.764 feet<sup>2</sup></i><br/>

In [21]:
floor_area_sqm = input('Tell me the floor area in Square Meters: ')
floor_area_sqm = int(floor_area_sqm)
floor_area_sqft = floor_area_sqm * 10.764
print(f"The floor area in square meters converted to square feet is : {floor_area_sqft}")

Tell me the floor area in Square Meters: 110
The floor area in square meters converted to square feet is : 1184.04


> **[ Question 5B ]** <br/>
Rewrite your code in Question 5A such that the code runs within a while loop. Only exit when the user keys in <b>exit</b>.<br/>
> Sample Output after you run your codes below: <br/>

> Tell me the floor area in Square Meters: 90 <br/>
> The floor area in square meter in square feet is: 968.76 <br/>
> Tell me the floor area in Square Meters: 130 <br/>
> The floor area in square meter in square feet is: 1399.32 <br/>
> Tell me the floor area in Square Meters: exit

> 📑  <i> Note: You can assume the user will only key in either a number, or "exit", hence no need for error checking. </i><br/>

In [22]:
floor_area_sqm = ""

while floor_area_sqm != "exit":
    floor_area_sqm = input('Tell me the floor area in Square Meters: ')
    if floor_area_sqm == "exit":
        break
    else:
        floor_area_sqft = int(floor_area_sqm) * 10.764
        print(f"The floor area in square meters converted to square feet is : {floor_area_sqft}")


Tell me the floor area in Square Meters: 90
The floor area in square meters converted to square feet is : 968.76
Tell me the floor area in Square Meters: 130
The floor area in square meters converted to square feet is : 1399.32
Tell me the floor area in Square Meters: exit


# Questions 6 - Functions

> **[ Question 6A ]** <br/>
All the addresses for HDB blocks are in the same pattern as shown in the examples below: <br/>
556, ANG MO KIO AVE 10 <br/>
28A, DOVER CRES <br/>
13, HOLLAND DR <br/>
9, MARSILING DR <br/>


> Write a function called **get_address** that will take one **address** as the input parameter (e.g. "13, HOLLAND DR") and only return the **street_name** - "HOLLAND DR", which is the part after the ", " <br/>

> 📑 Note: 
>>*You are required to string method - split() in your solution.* <br/>
>>*Take note that there is no space before the street name that the function returns*

In [30]:
def get_address(address="13, HOLLAND DR"):
    street_name = address.split(", ")[1].upper()
    return street_name
    

Then, test your function by calling it with the input parameter "28A, DOVER CRES"
You should see the same output as below:
'DOVER CRES'

In [31]:
get_address("28A, Dover Cres")

'DOVER CRES'

> **[ Question 6B ]** <br/>
> A piece of information about each HDB unit sold is this "storey_range", which shows the floor as a range from X to Y. The information is always in this format, shown by the examples below: <br/>
> 07 TO 09 <br/>
> 04 TO 06 <br/>
> 10 TO 12 <br/>
> 19 TO 21 <br/>

> Write a function called **"get_middle_floor"** that takes in one **storey_range** as the input parameter (e.g. "07 TO 09") <br/>
> Within that function, do the following:<br/>
>- Extract the first number (i.e. "07") and store in variable called **lower_end** <br/>
>- Extract the second number (i.e. "09") and store in variable called **higher_end** <br/>
>- Calculate the middle point of the two numbers and store in a variable called **middle** <br/>
>- Return the value stored in the variable **middle** as integer<br/>


> 📑 <i> Note: You will need to convert (or cast) the data type for variables, **lower_end** and **higher_end**, before calculating the middle point of the two values<i/>

In [32]:
def get_middle_floor(storey_range="07 TO 09"):
    lower_end = int(storey_range[0:2])
    higher_end = int(storey_range[-2:])
    middle = (higher_end + lower_end)/2
    return int(middle)

> Then, test your function by invoking it with the input parameter ""04 TO 06"" <br/>
> You should see the same output as below: <br/>
> 5

In [33]:
get_middle_floor("04 TO 06")

5

> **[ Question 6C ]** <br/>
> Write a function called **get_floor_category** that similarly takes in one **storey_range** as the input parameter (e.g. "04 TO 06"), but it should return the **floor_category**, which is decided based on the following logics: <br/> 
>- if the value in the **middle** variable is from 11 floor and above, your function should return **"High Floor"**
>- if the value in the **middle** variable is between 5 to 10, your function should return **"Middle Floor"**
>- if the value in the **middle** variable is below 5, your function should return **"Low Floor"**

> 📑 <i>  You'll need to call your function **get_middle_floor** from Question 6B within this new function **get_floor_category**.
<i/>

In [34]:
def get_floor_category(storey_range="04 TO 06"):
    middle = get_middle_floor(storey_range)
    
    floor_category = ""
    if middle >=11:
        print("High Floor")
    elif middle >=5:
        print("Middle Floor")
    else: 
        middle <5
        print("Low Floor")

> Then, test your function by invoking it with the input parameter ""04 TO 06"" <br/>
> You should see the same output as below: <br/>
> 'Middle Floor'

In [35]:
get_floor_category("04 TO 06")

Middle Floor


⬇️ Enter your name below as a string below.

In [36]:
myname = "TAN HUI HUI JENNY"

---
## END OF Capstone Assignment 1

- Well done everyone!