# List, Tuple, Dictionary, Set Operations

## Run The Following Code
Hit SHIFT + ENTER when your cusor is inside the cell of code.<br/>

> Create a variable to hold the values "apple", "banana", "chiku", "durian". Assign them to the variable <b>store</b> using a list.

In [1]:
store = ["apple", "banana", "chiku", "durian"]
print(store)

['apple', 'banana', 'chiku', 'durian']


In [2]:
type(store)

list

In [3]:
#print out banana
store[1]

'banana'

> Use a tuple instead.

In [4]:
store_tuple = ("apple", "banana", "chiku", "durian")
print(store_tuple)

('apple', 'banana', 'chiku', 'durian')


In [5]:
type(store_tuple)

tuple

In [6]:
#print out banana
store_tuple[1]

'banana'

> Using tuples to swap values in a variable

In [7]:
x = input("Key in a name: ")

Key in a name: tom


In [8]:
y = input("Key in another name: ")

Key in another name: dick


In [9]:
print(x)
print(y)

tom
dick


In [13]:
#Using another variable, swap the values of x with y.
z = (y, x)
print(z)

('tom', 'dick')


In [14]:
print(x)
print(y)

dick
tom


In [12]:
#Without using another variable, swap the values of x with y.
(y, x) = (x, y)

In [15]:
print(x)
print(y)

dick
tom


> Use a dictionary instead.

In [16]:
store_dict = {"fruit1":"apple", "fruit2":"banana", "fruit3":"chiku", "fruit4":"durian"}
print(store_dict)

{'fruit1': 'apple', 'fruit2': 'banana', 'fruit3': 'chiku', 'fruit4': 'durian'}


In [17]:
type(store_dict)

dict

In [18]:
store_dict.keys()

dict_keys(['fruit1', 'fruit2', 'fruit3', 'fruit4'])

In [19]:
store_dict.values()

dict_values(['apple', 'banana', 'chiku', 'durian'])

In [20]:
#print out banana
store_dict['fruit2']

'banana'

> Use a set instead.

In [21]:
store_set = {"apple", "banana", "chiku", "durian"}
print(store_set)

{'chiku', 'apple', 'banana', 'durian'}


In [22]:
type(store_set)

set

# !! Your Turn !!

## Replace the code marked as <..> COMPLETELY with your own.
For example:
length = <..> will be replaced by length = 10

# Question 1
1) Store [2,4,6,8,10] into a variable data<br/>
2) Print out the 1st element in this list.

In [23]:
data =  [2,4,6,8,10]
print(data[0]) #You should see the output 2

2


# Question 2

1) Store [1,3,5,7,9] into a variable data2<br/>
2) Print out the 3rd element in this list.

In [24]:
data2 =  [1,3,5,7,9] 
print(data2[2]) #You should see the output 5

5


# Question 3
1) Concatenate the two lists <b>data</b> and <b>data2</b> together into a variable, <b>data3</b>.<br/>
2) Print them out.<br/>

In [38]:
data3 = data + data2
print(data3)

[2, 4, 6, 8, 10, 1, 3, 5, 7, 9]


3) If they are not in the correct running sequence, sort them.<br/>
4) Print it out

In [40]:
data3.sort()
print(data3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Question 4

Let's try out mathematical operators on the lists and see if they work. <br/>
1) Multiply the list, <b>data3</b>, by 2. What do you see?<br/>

In [41]:
print(data3 * 2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


<i>Tips: Try out the other mathematical operators in the boxes below. Some may not work and may produce errors</i> 

In [42]:
#use +
print(data3 + 5)

TypeError: can only concatenate list (not "int") to list

In [43]:
#use -
print(data3 - 5)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [44]:
#use /
print(data3 / 5)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

<i>This shows that you cannot apply mathematical operators to a list the way you would to numeric data types.</i> 

# Question 5
1) Create a variable, <b>storage</b>, that stores the following:<br/><br/>
table<br/>
chair<br/>
fridge<br/>
washing machine<br/><br/>
2) print out the variable storage and verify the contents.
Hint: You should see ['table', 'chair', 'fridge', 'washing machine']

In [57]:
storage = ["table", "chair" , "fridge", "washing machine"]
print(storage)

['table', 'chair', 'fridge', 'washing machine']


# Question 6
1) You can add "aircon" into storage by doing <b>storage.append("aircon")</b>.<br/>
2) Do that, and print out the new storage variable to verify that "aircon" has been added.<br/>
Hint: You should see ['table', 'chair', 'fridge', 'washing machine', 'aircon']

In [58]:
storage.append("aircon")
print(storage)

['table', 'chair', 'fridge', 'washing machine', 'aircon']


# Question 7
1) You can remove "chair" from storage by doing <b>storage.remove("chair")</b>.<br/>
2) Do that, and print out the new storage variable to verify that "chair" has been removed.<br/>
Hint: You should see ['table', 'fridge', 'washing machine', 'aircon']

In [59]:
storage.remove("chair")
print(storage)

['table', 'fridge', 'washing machine', 'aircon']


# Question 8
1) <b>|value| in storage</b> allows you to check whether an item is inside the list.<br/>
2) For example, <b>"table" in storage</b> will return true.<br/>
3) Write the code to check if the item "fridge" is inside storage.<br/>

In [60]:
print("fridge" in storage)

True


# Question 9
1) Create a dictionary, <b>postal_to_town</b> that stores the following key-value pairs.<br/>
760702 --> Yishun
530406 --> Hougang
600212 --> Jurong East

In [61]:
postal_to_town = {
    760702: "Yishun",
    530406: "Hougang",
    600212: "Jurong East"
}

In [64]:
postal_to_town

{760702: 'Yishun', 530406: 'Hougang', 600212: 'Jurong East'}

2) Print out the town by referencing postal '760702'<br/>
You should see Yishun

In [67]:
postal_to_town[760702]

'Yishun'

3) Print out the town by referencing postal '530406'<br/>
You should see Hougang

In [69]:
postal_to_town[530406]

'Hougang'

4) Print out the town by referencing postal '600212'<br/>
You should see Jurong East

In [70]:
postal_to_town[600212]

'Jurong East'

4) Print out the town by referencing postal '138577'<br/>
What do you see?

In [71]:
postal_to_town[138577]

KeyError: 138577

# Question 10*

1) Decide on a data type to use for the following use case: <br/>
- I want to read in values and store them as I read them in sequentially.<br/>
- Order matters.<br/>
- Repeated values are ok.<br/>
- I want to be able to remove some of the items too.<br/>

2) When you have decided, create such a variable called <b>zoo2</b> and store the following values into it:<br/>
- lion<br/>
- tiger<br/>
- giraffe<br/>
- hippo<br/>
- monkey<br/>

In [79]:
zoo2 = ["lion", "tiger", "giraffe", "hippo", "monkey"]

3) Write code into the cell below such that you will prompt the user to tell you an animal, then store it into the existing data in the variable <b>zoo2</b>.<br/>
4) Then, run the cell below 3 times, and input the following values:<br/>
- bird<br/>
- panda<br/>
- monkey<br/>

In [82]:
animal = input("Name an animal: ")
zoo2.append(animal)

Name an animal: monkey


5) Print out the variable <b>zoo2</b>. It should contain the following in order:<br/>
- lion<br/>
- tiger<br>
- giraffe<br>
- hippo<br>
- monkey<br>
- bird<br>
- panda<br>
- monkey<br>

In [83]:
print(zoo2)

['lion', 'tiger', 'giraffe', 'hippo', 'monkey', 'bird', 'panda', 'monkey']


6) Write code into the cell below such that you will prompt the user to tell you an animal, then remove it from the existing data in the variable <b>zoo2</b>.<br/>
7) Then, run the cell below 3 times, and input the following values:<br/>
- tiger<br/>
- monkey<br/>
- giraffe<br/>

In [86]:
del_animal = input("Name an animal to remove: ")
zoo2.remove(del_animal)

Name an animal to remove: giraffe


8) Print out the variable <b>zoo2</b>. It should contain the following in order:<br/>
- lion<br/>
- hippo<br>
- bird<br>
- panda<br>
- monkey<br>

In [87]:
print(zoo2)

['lion', 'hippo', 'bird', 'panda', 'monkey']


# Question 11 *

1) Decide on a data type to use for the following use case: <br/>
- I want to read in a pair of key and values and store them.<br/>
- Order does not matter.<br/>
- Repeated values are ok.<br/>
- I want to be able to change some of the values for the keys too.<br/>

2) When you have decided, create such a variable called <b>zoo3</b> and store the following key - values into it:<br/>
- lion - c<br/>
- tiger - h<br/>
- giraffe - h<br/>
- hippo - h<br/>
- monkey - o<br/><br/>
<i>Note: key is lion, value is c</i>

In [88]:
zoo3 = {"lion" : "c",
        "tiger" : "h",
        "giraffe" : "h",
        "hippo" : "h",
        "monkey" : "o"
       }

3) Write code into the cell below such that you will prompt the user to tell you an animal.<br/>
4) Then, run the cell below 1 time, and input the following values:<br/>
- bird<br/>

In [89]:
animal = input("Name an animal: ")

Name an animal: bird


5) Write code into the cell below such that you will prompt the user to tell you whether the animal is a carnivore, herbivore or omnivore.<br/>
The user simply keys in c, h or o.<br/>
6) Then, run the cell below 1 time, and input the following values:<br/>
- o<br/>

In [91]:
diet = input("Is the animal a carnivore, herbivore or omnivore? Type your answer as 'c', 'h', 'o' :")

Is the animal a carnivore, herbivore or omnivore? Type your answer as 'c', 'h', 'o' :o


7) Add the new animal and its dietary preference into <b>zoo3</b>.<br/>
Print out <b>zoo3</b>.

In [94]:
zoo3[animal]= diet
print(zoo3)

{'lion': 'c', 'tiger': 'h', 'giraffe': 'h', 'hippo': 'h', 'monkey': 'o', 'bird': 'o'}


8) You realised you made a mistake with the dietary preference for the tiger earlier on. Write the code to change it from an 'h' to a 'c'.<br/>
Print out <b>zoo3</b>.

In [96]:
zoo3['tiger'] = "c"
print(zoo3)

{'lion': 'c', 'tiger': 'c', 'giraffe': 'h', 'hippo': 'h', 'monkey': 'o', 'bird': 'o'}
